apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: genai-service
  namespace: petclinic-prod
  labels:
    app.kubernetes.io/name: genai-service
    app.kubernetes.io/part-of: petclinic
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: genai-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
