apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-gateway
  namespace: petclinic-prod
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: petclinic
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: gateway
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api-gateway
