apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: petclinic-dev
  labels:
    app.kubernetes.io/name: config-server
    app.kubernetes.io/part-of: petclinic
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: config-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: config-server
        app.kubernetes.io/part-of: petclinic
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: server
    spec:
      serviceAccountName: config-server
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: config-server
          image: 231351515075.dkr.ecr.eu-central-1.amazonaws.com/petclinic-dev/config-server:305a1f1
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8888
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: GIT_REPO
              valueFrom:
                configMapKeyRef:
                  name: config-server-config
                  key: GIT_REPO
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          startupProbe:
            httpGet:
              path: /actuator/health
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: false
