apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: petclinic-dev
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: petclinic
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: gateway
data:
  CONFIG_SERVER_URL: "http://config-server:8888"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka/"
